### ISSUE TITLE
no release for 2018.*

### ISSUE THREAD

**Issue by albreche** [Digilent/Zybo-Z7-20-DMA#1]
Greetings, 
it seems the release for vivado 2018.3 is not ready yet. Nevertheless, it's said in the readme.md that such a release exists. Is there a planned date for the release ?

**Comment by albreche** [comment]
Ok, it's easy to build the project using the vivado python script. Btw, the example does not run on vivado 2018.3 but is ok with 2018.2

**Comment by artvvb** [comment]
I just uploaded the 2018.2 release. You should be able  to open the xpr file in the release in Vivado 2018.3 as well as 2018.2 (as usual, some IPs will need to be upgraded).
